server:
  port: 80

eureka:
  client:                                               #客户端注册 -> Eureka
    service-url:
      defaultZone: http://localhost:7001/eureka
    register-with-eureka: false
feign:
  hystrix:
    enabled: true
