server:
  port: 8001

mybatis:
  config-location: classpath:mybatis/mybatis.cfg.xml
  type-aliases-package: club.dafty.springcloud.pojo     #所有pojo别名类所在包
  mapper-locations: classpath:mybatis/mapper/**/*.xml
spring:
  application:
    name: microservice-provider                         #Eureka注册的名字就是从这取的
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource        #当前数据源操作类型 #mysql驱动包
    driver-class-name: org.gjt.mm.mysql.Driver
    url: jdbc:mysql://118.24.7.22:3306/cloudDB01
    username: psg
    password: psg
    dbcp2:
      min-idle: 5                                       #数据库连接池的最小维持连接数
      initial-size: 5                                   #初始化连接数
      max-total: 5                                      #最大连接数
      max-wait-millis: 200                              #等待连接获取最大超时时间
eureka:
  client:                                               #客户端注册 -> Eureka
    service-url:
      defaultZone: http://localhost:7001/eureka
  instance:                                             #自定义实例名称
    instance-id: provider:${server.port}
    prefer-ip-address: true                             #访问路径可以显示ip地址

info:                                                   #Actuator监控信息info
  app.name: dafty-microservice
  company.name: dafty.club
  build.artifactId: $project.artifactId$
  build.version: $project.version$


management:
  endpoints:
    web:
      exposure:
        include: "*"